---
title: "IISD Experimental Lakes Area_Phytoplankton"
output: pdf_document
date: "2025-03-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r phytoplankton in canadian lakes}
library(tidyverse)
rm(list=ls())

# read data
data_phyto_IISD <- read.csv('https://portal.edirepository.org/nis/dataviewer?packageid=edi.1557.3&entityid=f6e00309d88b6c726c4bbc7f917c70a0')

# convert date
data_phyto_IISD$date_collected <- as.Date(data_phyto_IISD$date_collected)
data_phyto_IISD <- data_phyto_IISD %>% mutate(year=year(date_collected),
                                              month=month(date_collected)) 

# how many lakes?
unique(data_phyto_IISD$monitoring_location_name)
## five lakes: "114 LA CB" "224 LA CB" "239 LA CB" "373 LA CB" "442 LA CB"

# how many species?
length(unique(data_phyto_IISD$species_code))  # 363 species

# stratum: "EPI"  "META" "HYP"; only use EPI and META; no EPI for 114 LA CB - a small lake
unique(data_phyto_IISD$stratum)

# annual sampling times of each lake
data_phyto_IISD %>% filter(stratum=="EPI") %>% group_by(monitoring_location_name, year) %>% summarise(num_sample=n_distinct(date_collected)) %>%
  ggplot(aes(x=year, y=num_sample, color=monitoring_location_name)) +
    geom_point() +
    geom_line()  

data_phyto_IISD %>% filter(stratum=="META") %>% group_by(monitoring_location_name, year) %>% summarise(num_sample=n_distinct(date_collected)) %>%
  ggplot(aes(x=year, y=num_sample, color=monitoring_location_name)) +
    geom_point() +
    geom_line()  


# use data from 1998 to 2020, month 5-10
data_phyto_filter <- data_phyto_IISD %>% filter(stratum=="EPI" | stratum=="META" & monitoring_location_name!="114 LA CB") %>%
  filter(year >= 1998 & year <= 2020) %>%
  filter(month >= 5 & month <= 10)
  
# check if there is duplicated rows
sum(duplicated(data_phyto_filter[,1:6]))  # 4032 rows

# merge duplicated rows: use the average of them
data_phyto_filter <- data_phyto_filter %>% group_by(monitoring_location_name, date_collected, stratum, depth_upper, depth_lower, species_code) %>% summarise_all(mean)

data_phyto_out <- data.frame(site=data_phyto_filter$monitoring_location_name, 
                             taxa_type="producer", 
                             ecosystem="aquatic", 
                             habitat_broad='lake', 
                             habitat_fine='lake', 
                             biome='temperate', 
                             guild='plant', 
                             herbivore='no',
                             year=data_phyto_filter$year,
                             month=data_phyto_filter$month,
                             day=day(data_phyto_filter$date_collected),
                             plot=data_phyto_filter$stratum)
##
data_phyto_out <- data_phyto_out %>% mutate(unique_ID=paste(data_phyto_out$site, data_phyto_out$habitat_fine, data_phyto_out$plot, sep='_'), 
                                            unit_abundance="mg/L", 
                                            scale_abundance="1L", 
                                            taxon_name=data_phyto_filter$species_code, 
                                            abundance=data_phyto_filter$biomass, 
                                            id_confidence=TRUE)
#### if biomass_conc = 0.0000, i used biomass_conc = 0.0001
data_phyto_out$abundance[data_phyto_out$abundance==0.0000] <- 0.0001

####
write.csv(data_phyto_out, 'harmonized_data/phytoplankton_IISD_lake_area.csv', row.names = F)
####
googledrive::drive_upload(media = file.path("harmonized_data/phytoplankton_IISD_lake_area.csv"), overwrite = T,
                          path = googledrive::as_id("https://drive.google.com/drive/folders/1zzesyCB6l88ZqG7rB5uYpIUUe81LCzOx"))

# epi: five lakes, meta: 4 lakes only. 

```

