---
title: "USVI_TCRMP"
output: pdf_document
date: "2025-01-20"
author: "Junna Wang"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r benthic cover algae}
library(librarian)
# Install missing packages and load needed libraries
shelf(tidyverse, googlesheets4, googledrive, readxl)
rm(list=ls())
#
path <- '../../../data_discovery/USVI_TCRMP/TCRMP_Master_Benthic_Cover_Feb2022.xlsx'
sheets_name <- excel_sheets(path)
benthic_cover <- read_excel(path, sheet="BenthicData")
site_metadata <- read_excel(path, sheet="SiteMetadata")
#
############################reading google sheet method does not work######################
# gs4_auth()
# path <- 'https://docs.google.com/spreadsheets/d/1If0CsxbG469kv6U_GyZ0t9ewAtlm03zx/edit#gid=697263468'
# sheets_name <- read_sheet(path)
# benthic_cover <- read_excel(path, sheet="BenthicData")
# #
# only use annually sampled data
benthic_cover_annual <- benthic_cover %>% filter(Period=="Annual") %>% select(c(SampleYear, SampleMonth, Location, Transect, CALG, RO, FLCY, LYNG, SCHIZ, EAC, AMPH, CLAD, DICT, HALI, LIAG, LOBO, MACA, MICRO, SARG))  # 15 taxon only. PEY and RAMI are removed because not completely sampled 
#
# there are 204 NA cells, filled with 0
benthic_cover_annual[is.na(benthic_cover_annual)] <- 0
sum(rowSums(benthic_cover_annual[, 5:19]) <= 0.0)  # we do not have locations without algae
#
benthic_cover_long <- pivot_longer(benthic_cover_annual, cols = -c(SampleYear, SampleMonth, Location, Transect), names_to = "taxon_name", values_to = "abundance") %>% filter(abundance > 0 & !is.na(abundance))
#
# add habitat fine information
benthic_cover_long <- benthic_cover_long %>% left_join(site_metadata[,c("Location", "ReefComplex")], by='Location')
#
benthic_cover_long <- benthic_cover_long %>% rename(year=SampleYear, month=SampleMonth, plot=Location, subplot=Transect, habitat_fine=ReefComplex)
benthic_cover_out  <- benthic_cover_long %>% mutate(site='USVI') %>% mutate(taxa_type="producer", ecosystem="aquatic", habitat_broad='marine', biome='tropic', guild='benthic algae', herbivore='no', unit_abundance='%', scale_abundance='per transect', unique_ID=paste(site, habitat_fine, plot, sep='_'), id_confidence=TRUE)
#
# change the order of different columns
benthic_cover_out <- benthic_cover_out[,c("site", "taxa_type", "ecosystem", "habitat_broad", "habitat_fine", "biome", "guild", "herbivore", "year", "month", "plot", "subplot", "unique_ID", "unit_abundance", "scale_abundance", "taxon_name", "abundance", "id_confidence")]
#
write.csv(benthic_cover_out, 'harmonized_data/USVI_benthic_cover_algae.csv', row.names = F)
#
googledrive::drive_upload(media = file.path("harmonized_data/USVI_benthic_cover_algae.csv"), overwrite = T,
                          path = googledrive::as_id("https://drive.google.com/drive/folders/1d4uwv5Eq5u5hFw22po_7sK-_Uwisc65w"))

```

```{r benthic cover filter feeder}
library(librarian)
# Install missing packages and load needed libraries
shelf(tidyverse, googlesheets4, googledrive, readxl)
rm(list=ls())
#
path <- '../../../data_discovery/USVI_TCRMP/TCRMP_Master_Benthic_Cover_Feb2022.xlsx'
sheets_name <- excel_sheets(path)
benthic_cover <- read_excel(path, sheet="BenthicData")
site_metadata <- read_excel(path, sheet="SiteMetadata")
#
############################reading google sheet method does not work######################
# gs4_auth()
# path <- 'https://docs.google.com/spreadsheets/d/1If0CsxbG469kv6U_GyZ0t9ewAtlm03zx/edit#gid=697263468'
# sheets_name <- read_sheet(path)
# benthic_cover <- read_excel(path, sheet="BenthicData")
# #
# only use annually sampled data
benthic_cover_annual <- benthic_cover %>% filter(Period=="Annual") %>% select(c(-Period, -FilmDate, -NoPts, -AnalysisBy, -AnalysisDate, 
                  -CALG, -RO, -FLCY, -LYNG, -SCHIZ, -EAC, -AMPH, -CLAD, -DICT, -HALI, -LIAG, -LOBO, -MACA, -MICRO, -SARG,   # algae
                  -BBD, -BL, -DCOR, -DSD, -PLA, -SCTLD, -WBD, -YBD, # coral conditions
                  -B, -P, -R, -S, -TWS, -UNK,  # non-living
                  -PEY, -RAMI, -PC, -SCTLD,	-Check,	-Notes)) # missing data and others
#
# there are 6 NA cells, filled with 0
benthic_cover_annual[is.na(benthic_cover_annual)] <- 0
sum(rowSums(benthic_cover_annual[, 5:88]) <= 0.0)  # we do not have locations without algae
#
benthic_cover_long <- pivot_longer(benthic_cover_annual, cols = -c(SampleYear, SampleMonth, Location, Transect), names_to = "taxon_name", values_to = "abundance") %>% filter(abundance > 0 & !is.na(abundance))
#
# add habitat fine information
benthic_cover_long <- benthic_cover_long %>% left_join(site_metadata[,c("Location", "ReefComplex")], by='Location')
#
benthic_cover_long <- benthic_cover_long %>% rename(year=SampleYear, month=SampleMonth, plot=Location, subplot=Transect, habitat_fine=ReefComplex)
benthic_cover_out  <- benthic_cover_long %>% mutate(site='USVI', taxa_type="filter_feeder", ecosystem="aquatic", habitat_broad='marine', biome='tropic', guild='benthic consumer', herbivore='unsure', unit_abundance='%', scale_abundance='per transect', unique_ID=paste(site, habitat_fine, plot, sep='_'), id_confidence=TRUE)
#
# change the order of different columns
benthic_cover_out <- benthic_cover_out[,c("site", "taxa_type", "ecosystem", "habitat_broad", "habitat_fine", "biome", "guild", "herbivore", "year", "month", "plot", "subplot", "unique_ID", "unit_abundance", "scale_abundance", "taxon_name", "abundance", "id_confidence")]
#
write.csv(benthic_cover_out, 'harmonized_data/USVI_benthic_cover_filter_feeder.csv', row.names = F)
#
googledrive::drive_upload(media = file.path("harmonized_data/USVI_benthic_cover_filter_feeder.csv"), overwrite = T,
                          path = googledrive::as_id("https://drive.google.com/drive/folders/1d4uwv5Eq5u5hFw22po_7sK-_Uwisc65w"))

```


```{r fish}
library(librarian)
# Install missing packages and load needed libraries
shelf(tidyverse, googlesheets4, googledrive, readxl)
rm(list=ls())
#
path <- '../../../data_discovery/USVI_TCRMP/TCRMP_Master_Fish_Census_Aug2022.xlsx'
sheets_name <- excel_sheets(path)
fish_data <- read_excel(path, sheet="FishData")
site_metadata <- read_excel(path, sheet="SiteMetadata")
#
############################reading google sheet method does not work######################
# gs4_auth()
# path <- 'https://docs.google.com/spreadsheets/d/1-FvhfMAFs5hNEqmYm0EJd2P23BBYeV7_/edit#gid=926142160'
# sheets_name <- read_sheet(path)
# benthic_cover <- read_excel(path, sheet="BenthicData")
# #
# only use annually sampled data
fish_data_annual <- fish_data %>% filter(Period=="Annual" & Metric=='Biomass') %>% select(-Period, -Year, -CommonName, -Metric, -`0-5`, -`6-10`, -`11-20`, -`21-30`, -`31-40`, -`41-50`, -`51-60`, -`61-70`, -`71-80`, -`81-90`, -`91-100`)
#
# add habitat fine information
fish_data_annual <- fish_data_annual %>% left_join(site_metadata[, c("Location", "ReefComplex")], by='Location')
#
fish_data_out <- fish_data_annual %>% rename(year=SampleYear, month=Month, plot=Location, subplot=Transect, habitat_fine=ReefComplex, taxon_name=ScientificName, abundance=Total)
#
fish_data_out  <- fish_data_out %>% mutate(site='USVI') %>% mutate(taxa_type="consumer", ecosystem="aquatic", habitat_broad='marine', biome='tropic', guild='fish', unit_abundance='biomass', scale_abundance='per transect', unique_ID=paste(site, habitat_fine, plot, sep='_'), id_confidence=TRUE) %>% mutate(herbivore=case_when(TrophicGroup %in% c("herb", "omni") ~ "yes",
                           TrophicGroup %in% c("plank", "pisc", "inv", "spng", "unk") ~ "no"))
#
fish_data_out <- fish_data_out[,c("site", "taxa_type", "ecosystem", "habitat_broad", "habitat_fine", "biome", "guild", "herbivore", "year", "month", "plot", "subplot", "unique_ID", "unit_abundance", "scale_abundance", "taxon_name", "abundance", "id_confidence", "TrophicGroup")]
#
write.csv(fish_data_out, 'harmonized_data/USVI_fish_census.csv', row.names = F)
#
googledrive::drive_upload(media = file.path("harmonized_data/USVI_fish_census.csv"), overwrite = T,
                          path = googledrive::as_id("https://drive.google.com/drive/folders/1d4uwv5Eq5u5hFw22po_7sK-_Uwisc65w"))

```

